name: 🐛 Reporte de Bug
description: Reportar um problema ou erro encontrado
title: "[BUG]: "
body:
  - type: textarea
    id: bug-description
    attributes:
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Passos para reproduzir
      description: Explique como reproduzir o bug.
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Role até '...'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento esperado
      description: O que você esperava que acontecesse.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Informações adicionais
      description: Logs, prints de tela ou qualquer outro detalhe que ajude a resolver o bug.
