name: 🚀 Solicitação de Feature
description: Sugerir uma nova funcionalidade ou melhoria
title: "[FEATURE]: "
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Descrição da funcionalidade
      description: Explique de forma clara o que deve ser desenvolvido.
    validations:
      required: true

  - type: textarea
    id: business-rules
    attributes:
      label: Regras de negócio
      description: Liste as regras de negócio que devem ser aplicadas.

  - type: textarea
    id: screens
    attributes:
      label: Prints/Telas
      description: Anexe ou descreva as telas que devem ser feitas (wireframes, mockups ou prints).

  - type: textarea
    id: notes
    attributes:
      label: Observações
      description: Informações extras relevantes para o desenvolvimento.
