name: 🚀 Solicitação de Feature
description: Sugerir uma nova funcionalidade ou melhoria
title: "[FEATURE]: "
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Descrição da funcionalidade
      description: Explique a funcionalidade ou melhoria desejada.
    validations:
      required: true

  - type: textarea
    id: problem-to-solve
    attributes:
      label: Problema a ser resolvido
      description: Qual problema essa funcionalidade resolve? Por que seria útil?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Solução proposta
      description: Caso já tenha uma ideia de como implementar, descreva aqui.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
      description: Outras formas que você pensou para resolver esse problema.

  - type: textarea
    id: additional-information
    attributes:
      label: Informações adicionais
      description: Prints, exemplos, referências ou qualquer outro detalhe relevante.
